//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STAJORNEKCALISMA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class STAJCALISMASIEntities : DbContext
    {
        public STAJCALISMASIEntities()
            : base("name=STAJCALISMASIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_HAT> TBL_HAT { get; set; }
        public virtual DbSet<TBL_HATSATIS> TBL_HATSATIS { get; set; }
        public virtual DbSet<TBL_KULLANICI> TBL_KULLANICI { get; set; }
        public virtual DbSet<VW_HATSATIS> VW_HATSATIS { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_hat(Nullable<int> iD, Nullable<System.Guid> sIFRELIID, string hAT_NO, Nullable<byte> hAT_DURUM, Nullable<System.DateTime> kAYITTARIHI, Nullable<byte> hATSATIS_DURUM, Nullable<int> hatislem)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var sIFRELIIDParameter = sIFRELIID.HasValue ?
                new ObjectParameter("SIFRELIID", sIFRELIID) :
                new ObjectParameter("SIFRELIID", typeof(System.Guid));
    
            var hAT_NOParameter = hAT_NO != null ?
                new ObjectParameter("HAT_NO", hAT_NO) :
                new ObjectParameter("HAT_NO", typeof(string));
    
            var hAT_DURUMParameter = hAT_DURUM.HasValue ?
                new ObjectParameter("HAT_DURUM", hAT_DURUM) :
                new ObjectParameter("HAT_DURUM", typeof(byte));
    
            var kAYITTARIHIParameter = kAYITTARIHI.HasValue ?
                new ObjectParameter("KAYITTARIHI", kAYITTARIHI) :
                new ObjectParameter("KAYITTARIHI", typeof(System.DateTime));
    
            var hATSATIS_DURUMParameter = hATSATIS_DURUM.HasValue ?
                new ObjectParameter("HATSATIS_DURUM", hATSATIS_DURUM) :
                new ObjectParameter("HATSATIS_DURUM", typeof(byte));
    
            var hatislemParameter = hatislem.HasValue ?
                new ObjectParameter("hatislem", hatislem) :
                new ObjectParameter("hatislem", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_hat", iDParameter, sIFRELIIDParameter, hAT_NOParameter, hAT_DURUMParameter, kAYITTARIHIParameter, hATSATIS_DURUMParameter, hatislemParameter);
        }
    
        public virtual int sp_hatsatis(Nullable<int> iD, Nullable<System.Guid> sIFRELIID, Nullable<System.DateTime> sATISTARIH, Nullable<int> hATSATISKULLANICIID, Nullable<int> hATSATISHATID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var sIFRELIIDParameter = sIFRELIID.HasValue ?
                new ObjectParameter("SIFRELIID", sIFRELIID) :
                new ObjectParameter("SIFRELIID", typeof(System.Guid));
    
            var sATISTARIHParameter = sATISTARIH.HasValue ?
                new ObjectParameter("SATISTARIH", sATISTARIH) :
                new ObjectParameter("SATISTARIH", typeof(System.DateTime));
    
            var hATSATISKULLANICIIDParameter = hATSATISKULLANICIID.HasValue ?
                new ObjectParameter("HATSATISKULLANICIID", hATSATISKULLANICIID) :
                new ObjectParameter("HATSATISKULLANICIID", typeof(int));
    
            var hATSATISHATIDParameter = hATSATISHATID.HasValue ?
                new ObjectParameter("HATSATISHATID", hATSATISHATID) :
                new ObjectParameter("HATSATISHATID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_hatsatis", iDParameter, sIFRELIIDParameter, sATISTARIHParameter, hATSATISKULLANICIIDParameter, hATSATISHATIDParameter);
        }
    
        public virtual int sp_hatsatisdurumdegistir(Nullable<int> iD, Nullable<byte> hAT_DURUM)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var hAT_DURUMParameter = hAT_DURUM.HasValue ?
                new ObjectParameter("HAT_DURUM", hAT_DURUM) :
                new ObjectParameter("HAT_DURUM", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_hatsatisdurumdegistir", iDParameter, hAT_DURUMParameter);
        }
    
        public virtual int sp_hatsatisdurumdegistir2(Nullable<int> iD, Nullable<byte> hATSATIS_DURUM)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var hATSATIS_DURUMParameter = hATSATIS_DURUM.HasValue ?
                new ObjectParameter("HATSATIS_DURUM", hATSATIS_DURUM) :
                new ObjectParameter("HATSATIS_DURUM", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_hatsatisdurumdegistir2", iDParameter, hATSATIS_DURUMParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_kullanici(Nullable<int> iD, Nullable<System.Guid> sIFRELIID, string kULLANICI_ADI, string kULLANICI_SOYADI, string kULLANICI_MAIL, string kULLANICI_TEL, string kULLANICI_SIFRE, Nullable<System.DateTime> kAYITTARIHI, string kULLANICI_ADI_SOYADI, Nullable<int> islem)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var sIFRELIIDParameter = sIFRELIID.HasValue ?
                new ObjectParameter("SIFRELIID", sIFRELIID) :
                new ObjectParameter("SIFRELIID", typeof(System.Guid));
    
            var kULLANICI_ADIParameter = kULLANICI_ADI != null ?
                new ObjectParameter("KULLANICI_ADI", kULLANICI_ADI) :
                new ObjectParameter("KULLANICI_ADI", typeof(string));
    
            var kULLANICI_SOYADIParameter = kULLANICI_SOYADI != null ?
                new ObjectParameter("KULLANICI_SOYADI", kULLANICI_SOYADI) :
                new ObjectParameter("KULLANICI_SOYADI", typeof(string));
    
            var kULLANICI_MAILParameter = kULLANICI_MAIL != null ?
                new ObjectParameter("KULLANICI_MAIL", kULLANICI_MAIL) :
                new ObjectParameter("KULLANICI_MAIL", typeof(string));
    
            var kULLANICI_TELParameter = kULLANICI_TEL != null ?
                new ObjectParameter("KULLANICI_TEL", kULLANICI_TEL) :
                new ObjectParameter("KULLANICI_TEL", typeof(string));
    
            var kULLANICI_SIFREParameter = kULLANICI_SIFRE != null ?
                new ObjectParameter("KULLANICI_SIFRE", kULLANICI_SIFRE) :
                new ObjectParameter("KULLANICI_SIFRE", typeof(string));
    
            var kAYITTARIHIParameter = kAYITTARIHI.HasValue ?
                new ObjectParameter("KAYITTARIHI", kAYITTARIHI) :
                new ObjectParameter("KAYITTARIHI", typeof(System.DateTime));
    
            var kULLANICI_ADI_SOYADIParameter = kULLANICI_ADI_SOYADI != null ?
                new ObjectParameter("KULLANICI_ADI_SOYADI", kULLANICI_ADI_SOYADI) :
                new ObjectParameter("KULLANICI_ADI_SOYADI", typeof(string));
    
            var islemParameter = islem.HasValue ?
                new ObjectParameter("islem", islem) :
                new ObjectParameter("islem", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_kullanici", iDParameter, sIFRELIIDParameter, kULLANICI_ADIParameter, kULLANICI_SOYADIParameter, kULLANICI_MAILParameter, kULLANICI_TELParameter, kULLANICI_SIFREParameter, kAYITTARIHIParameter, kULLANICI_ADI_SOYADIParameter, islemParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
