//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STAJORNEKCALISMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_HAT()
        {
            this.TBL_HATSATIS = new HashSet<TBL_HATSATIS>();
        }
    
        public int ID { get; set; }
        public Nullable<System.Guid> SIFRELIID { get; set; }
        public string HAT_NO { get; set; }
        public Nullable<byte> HAT_DURUM { get; set; }
        public Nullable<System.DateTime> KAYITTARIH { get; set; }
        public Nullable<byte> HATSATIS_DURUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_HATSATIS> TBL_HATSATIS { get; set; }
    }
}
