//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STAJORNEKCALISMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_KULLANICI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_KULLANICI()
        {
            this.TBL_HATSATIS = new HashSet<TBL_HATSATIS>();
        }
    
        public int ID { get; set; }
        public Nullable<System.Guid> SIFRELIID { get; set; }
        public string KULLANICI_ADI { get; set; }
        public string KULLANICI_SOYADI { get; set; }
        public string KULLANICI_MAIL { get; set; }
        public string KULLANICI_TEL { get; set; }
        public string KULLANICI_SIFRE { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string KULLANICI_ADI_SOYADI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_HATSATIS> TBL_HATSATIS { get; set; }
    }
}
