//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STAJORNEKCALISMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HATSATIS
    {
        public int ID { get; set; }
        public Nullable<System.Guid> SIFRELIID { get; set; }
        public Nullable<System.DateTime> SATISTARIH { get; set; }
        public int HATSATISKULLANICIID { get; set; }
        public int HATSATISHATID { get; set; }
    
        public virtual TBL_HAT TBL_HAT { get; set; }
        public virtual TBL_KULLANICI TBL_KULLANICI { get; set; }
    }
}
